version: '3.5'

volumes:
  nginx-conf:
  nginx-vhost:
  nginx-html:

services:
  reverse_proxy:
    image: nginx:1-alpine
    container_name: reverse_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
  
  dockergen:
    image: jwilder/docker-gen:0.7.3
    container_name: dockergen
    depends_on:
      - reverse_proxy
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    command:
      "-notify-sighup reverse_proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"

networks:
  default:
    external:
      name: nginx-proxy