version: '3.5'

volumes:
  nginx-conf:
  nginx-vhost:
  nginx-html:
  letsencrypt-certs:

services:
  reverse_proxy:
    image: nginx:1-alpine
    container_name: reverse_proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - letsencrypt-certs:/etc/nginx/certs:ro
  
  dockergen:
    image: jwilder/docker-gen:0.7.3
    container_name: dockergen
    restart: unless-stopped
    depends_on:
      - reverse_proxy
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - letsencrypt-certs:/etc/nginx/certs:ro
    command:
      "-notify-sighup reverse_proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.9.1
    container_name: letsencrypt
    restart: unless-stopped
    depends_on:
      - reverse_proxy
      - dockergen
    volumes:
      - letsencrypt-certs:/etc/nginx/certs:rw
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: dockergen
      NGINX_PROXY_CONTAINER: reverse_proxy

networks:
  default:
    external:
      name: nginx-proxy
